# Generated by Django 5.2.3 on 2025-07-04 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[
                    ('Love', 'Love'),
                    ('Career', 'Career'),
                    ('Life', 'Life'),
                    ('Family', 'Family'),
                    ('School', 'School'),
                    ('Other', 'Other')
                ], max_length=20)),
                ('message', models.TextField(max_length=1000)),
                ('feeling', models.CharField(choices=[
                    ('yes', 'Yes'),
                    ('no', 'No'),
                    ('prefer-not-say', 'Prefer not to say')
                ], max_length=20)),
                ('anonymous', models.BooleanField(default=True)),
                ('ai_response_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LowkeyWall.confession')),
            ],
        ),
    ]

