# Generated by Django 5.2.3 on 2025-07-05 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LowkeyWall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='confession',
            name='topic',
            field=models.CharField(choices=[('love', 'Love'), ('career', 'Career'), ('life', 'Life')], max_length=20),
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='LowkeyWall.confession')),
            ],
            options={
                'unique_together': {('confession', 'session_key')},
            },
        ),
    ]
