# Generated by Django 5.2.3 on 2025-07-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LowkeyWall', '0002_confession_user_alter_confession_topic_upvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Supporter'), ('premium', 'Contributor'), ('ultimate', 'Patron')], max_length=50, unique=True)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('perks', models.TextField(help_text='Comma-separated list of perks')),
            ],
        ),
    ]
