# Generated by Django 5.2.3 on 2025-07-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LowkeyWall', '0004_alter_confession_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='user',
        ),
        migrations.AddField(
            model_name='confession',
            name='display_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
