# Generated by Django 5.2.3 on 2025-07-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LowkeyWall', '0006_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='upvoted_ips',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
