# Generated by Django 5.2.4 on 2025-07-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LowkeyWall", "0007_confession_upvoted_ips"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confession",
            name="topic",
            field=models.CharField(
                choices=[
                    ("Love", "Love"),
                    ("Career", "Career"),
                    ("Life", "Life"),
                    ("Family", "Family"),
                    ("School", "School"),
                    ("Other", "Other"),
                    ("Mental Health", "Mental Health"),
                    ("Friendship", "Friendship"),
                    ("Finance", "Finance"),
                    ("Addiction", "Addiction"),
                    ("Loneliness", "Loneliness"),
                    ("Relationships", "Relationships"),
                    ("Spirituality", "Spirituality"),
                    ("Success", "Success"),
                    ("Failure", "Failure"),
                    ("Secrets", "Secrets"),
                    
                ],
                max_length=100,
            ),
        ),
    ]
