# Generated by Django 5.2.3 on 2025-07-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LowkeyWall', '0008_alter_confession_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='feeling',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Angry', 'Angry'), ('Confused', 'Confused'), ('Anxious', 'Anxious')], max_length=20),
        ),
    ]
